//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_ecole.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eleves
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Eleves()
        {
            this.Absences = new HashSet<Absences>();
            this.Notes = new HashSet<Notes>();
        }
    
        public int idEleve { get; set; }
        public int idUser { get; set; }
        public int ID_Classe { get; set; }
        public System.DateTime dateNaissance { get; set; }
        public string lieuNaissance { get; set; }
        public string InfoMedicales { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Absences> Absences { get; set; }
        public virtual Classes Classes { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Notes> Notes { get; set; }
    }
}
