//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_ecole.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bd_EcoleEntities : DbContext
    {
        public bd_EcoleEntities()
            : base("name=bd_EcoleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Absences> Absences { get; set; }
        public virtual DbSet<Classes> Classes { get; set; }
        public virtual DbSet<Cours> Cours { get; set; }
        public virtual DbSet<Eleves> Eleves { get; set; }
        public virtual DbSet<Matieres> Matieres { get; set; }
        public virtual DbSet<Messages> Messages { get; set; }
        public virtual DbSet<Niveaux> Niveaux { get; set; }
        public virtual DbSet<Notes> Notes { get; set; }
        public virtual DbSet<Professeurs> Professeurs { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<VUsers_Eleves> VUsers_Eleves { get; set; }
        public virtual DbSet<VEleves> VEleves { get; set; }
    }
}
