//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_ecole.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEleves
    {
        public int idEleve { get; set; }
        public int idUser { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string email { get; set; }
        public int ID_Classe { get; set; }
        public System.DateTime dateNaissance { get; set; }
        public string lieuNaissance { get; set; }
        public string InfoMedicales { get; set; }
        public byte[] dateCreation { get; set; }
    }
}
